name: Gitleaks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/cache@v6
        id: gitleaks
        with:
          path: ~/go/bin/gitleaks
          key: ${{ runner.os }}-gitleaks-8.30.1
      - name: install Gitleaks
        if: steps.gitleaks.outputs.cache-hit != 'true'
        run: go install github.com/zricethezav/gitleaks/v8@v8.30.1
      - name: detect committed secrets
        run: "$HOME/go/bin/gitleaks" git --redact --no-banner
